---
name: "npm"

on:
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:

  check:
    name: Build with npm
    runs-on: ubuntu-latest
    steps:
    - name: Set REPOSITORY
      run: echo "REPOSITORY=${GITHUB_REPOSITORY#*/}" >> "${GITHUB_ENV}"
    - name: Check out
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Setup
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 14
    - name: Build
      if: github.ref == 'FIXME'
      run: npm install && npm run dist
    - name: Upload artifacts
      uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
      with:
        name: ${{ env.REPOSITORY }}
        path: dist/
